### PR TITLE
Add devise

### PR DESCRIPTION
**Pull request by Mithi-code**
### Blog app: add devise

- Build a web app that requires the user to log in.
- Use devise gem for authentication.
- Remove current_user method in ApplicationController, devise will provide us with one.
- User logs in with a combination of email and password.
- Can reset password.
- Ask for confirmation of email.

### CODE REVIEW

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED 🍾✔🎉**
Hello @Mithi-code 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Github inline comments feature is used properly.
- You asked for the changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brytebee** [comment]
Hello, @emmanuellekamwa 👋👋,

Thanks for the warm-hearted review 👀👀.



I'll go ahead to merge and move on to the next milestone 🏁🏁.

**_Happy Hacking 😄😄_**

**Comment by brytebee** [comment]
We've been asked for [separate reviews in this MILESTONE.](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md)

image

Kindly review.

**Review by VICTOR-CHUKWU — APPROVED** [review]
Hi @brytebee , 
# STATUS: APPROVED! 🥇 💯 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
